---
- name: Check if inotify-tools is installed
  ansible.builtin.package:
    name: inotify-tools
    state: present

- name: Create directory for configuration file
  ansible.builtin.file:
    path: "{{ config_directory }}"
    state: directory

- name: Deploy configuration file for file monitoring
  ansible.builtin.template:
    src: file_action_mapping.yml.j2
    dest: "{{ config_directory }}/file_action_mapping.yml"
    mode: '0644'

- name: Debug file_action_mappings
  ansible.builtin.debug:
    var: item
  loop: "{{ file_action_mappings }}"


- name: Generate vars_files for each action
  ansible.builtin.template:
    src: vars_template.yml.j2
    dest: "{{ config_directory }}/{{ item.vars_file }}"
    vars:
      vars: "{{ item.vars }}"
  loop: "{{ file_action_mappings }}"
  when: item.vars_file is defined and item.vars is defined


- name: Deploy the file monitoring script
  ansible.builtin.template:
    src: file_monitor_script.sh.j2
    dest: "{{ monitor_script_path }}"
    mode: '0755'

- name: Create systemd service for file monitoring
  ansible.builtin.template:
    src: file_monitor_service.j2
    dest: "{{ systemd_service_path }}"
    mode: '0644'

- name: Reload systemd to recognize the new service
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start file monitoring service
  ansible.builtin.systemd:
    name: "{{ systemd_service_name }}"
    enabled: true
    state: started
