---
- name: Download Git repo and run playbook
  ansible.builtin.git:
    repo: "{{ git_repo_url }}"
    dest: "{{ git_repo_dest }}"
  register: git_result

- name: Run Ansible playbook
  ansible.builtin.command:
    cmd: ansible-playbook "{{ playbook_path }}"
  when: git_result.changed
